# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default
highlight_theme: default
url     : https://daemyung.github.io
baseurl :
title   : 삼각형의 블로그
description: 다양한 정보를 공유하기 위해 만들어진 공간입니다.

## => Language and Timezone
##############################
lang: ko
timezone: KR

## => Author and Social
##############################
author:
  type      :
  name      : Daemyung Jang
  url       :
  avatar    :
  bio       :
  email     : dm86.jang@gmail.com
  facebook  :
  twitter   :
  weibo     :
  googleplus:
  telegram  :
  medium    :
  zhihu     :
  douban    :
  linkedin  : djang-88b01b91
  github    : daemyung
  npm       :


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: daemyung/daemyung.github.io
repository_tree: main


## => Paths
##############################
paths:
  root    :
  home    :
  archive :
  rss     :


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0

## TOC
toc:
  selectors:


## => Markdown Enhancements
##############################
## Mathjax
mathjax:
mathjax_autoNumber:

## Mermaid
mermaid:

## Chart
chart:


## => Paginate
##############################
paginate: 8
paginate_path: /page:num


## => Sources
##############################
sources:


## => Sharing
##############################
sharing:
  provider: false
 
  ## AddThis
  addthis:
    id:


## => Comments
##############################
comments:
  provider: false

  ## Disqus
  disqus:
    shortname: 

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    :
    clientSecret:
    repository  :
    owner       :
    admin:

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      :
    app_key     :
    placeholder :
    visitor     :
    meta        :


## => Pageview
##############################
pageview:
  provider: false

  ## Leancloud
  leancloud:
    app_id    :
    app_key   :
    app_class :


## => Search
##############################
search:
  provider: default

  ## Google Custom Search Engine
  google:
    custom_search_engine_id:


## => Analytics
##############################
analytics:
  provider: false

  ## Google Analytics
  google:
    tracking_id :
    anonymize_ip: false


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
